import Foundation

enum Copy {
    static let appName = String(localized: "app.name")
    static let history = String(localized: "navigation.history")
    static let dictionary = String(localized: "navigation.dictionary")
    static let settings = String(localized: "navigation.settings")
    static let startRecording = String(localized: "recording.start")
    static let stopRecording = String(localized: "recording.stop")
    static let cancelRecording = String(localized: "recording.cancel")
    static let listening = String(localized: "recording.listening")
    static let preparing = String(localized: "recording.preparing")
    static let transcribing = String(localized: "recording.transcribing")
    static let inserting = String(localized: "recording.inserting")
    static let recordingFailed = String(localized: "recording.failed")
    static let cancelled = String(localized: "recording.cancelled")
    static let noHistory = String(localized: "history.empty.title")
    static let noHistoryDetail = String(localized: "history.empty.detail")
    static let searchHistory = String(localized: "history.search")
    static let searchDictionary = String(localized: "dictionary.search")
    static let addEntry = String(localized: "dictionary.add")
    static let all = String(localized: "dictionary.filter.all")
    static let vocabulary = String(localized: "dictionary.filter.vocabulary")
    static let corrections = String(localized: "dictionary.filter.corrections")
    static let heard = String(localized: "dictionary.heard")
    static let written = String(localized: "dictionary.written")
    static let preferredPhrase = String(localized: "dictionary.preferred")
    static let enabled = String(localized: "dictionary.enabled")
    static let delete = String(localized: "common.delete")
    static let save = String(localized: "common.save")
    static let cancel = String(localized: "common.cancel")
    static let copyText = String(localized: "common.copyText")
    static let retryInsertion = String(localized: "common.retryInsertion")
    static let deleteAllHistory = String(localized: "history.deleteAll")
    static let exportHistory = String(localized: "history.export")
    static let privacy = String(localized: "settings.privacy")
    static let shortcut = String(localized: "settings.shortcut")
    static let speech = String(localized: "settings.speech")
    static let insertion = String(localized: "settings.insertion")
    static let about = String(localized: "settings.about")
    static let keepHistory = String(localized: "settings.keepHistory")
    static let retention = String(localized: "settings.retention")
    static let accessibility = String(localized: "permissions.accessibility")
    static let microphone = String(localized: "permissions.microphone")
    static let openSettings = String(localized: "permissions.openSettings")
    static let checkAgain = String(localized: "permissions.checkAgain")
}
