import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import { open, save, confirm } from '@tauri-apps/plugin-dialog';
import { createIcons, LayoutDashboard, History, BookOpen, ChartNoAxesCombined, Cpu, Settings, Mic, Square, Copy, Trash2, Pin, Download, X, Check, ArrowUpRight, CircleHelp } from 'lucide';
import './style.css';

interface Entry {id:string;kind:string;sourcePhrase:string;targetPhrase:string|null;notes:string|null;isEnabled:boolean;createdAt:string;updatedAt:string}
interface Transcript {id:string;timestamp:string;originalTranscript:string;correctedText:string;duration:number;insertionResult:string;correctionAudit:{heard:string;written:string}[];isPinned:boolean}
interface Preferences {model:string;keepHistory:boolean;retention:string;recordingMode:string;shortcut:string;appearance:string;onboardingDone:boolean;autoInsert:boolean}
interface Snapshot {data:{preferences:Preferences;history:Transcript[];dictionary:Entry[];recovery:string|null};phase:string;models:{id:string;name:string;bytes:number}[];installed:string[];ready:boolean;settingUp:boolean;notice:string|null;shortcutError:string|null;capability:string;platform:string;version:string}
const root=document.querySelector<HTMLDivElement>('#app')!;
const overlay=new URLSearchParams(location.search).has('overlay');
let state:Snapshot;let section='dashboard';let search='';let localError='';let progress='';let busy=false;let editing:string|null=null;
const names:Record<string,string>={dashboard:'Dashboard',history:'History',dictionary:'Dictionary',statistics:'Statistics',models:'AI models',settings:'Settings'};
const glyphs:Record<string,string>={dashboard:'layout-dashboard',history:'history',dictionary:'book-open',statistics:'chart-no-axes-combined',models:'cpu',settings:'settings'};
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const icon=(name:string)=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
const button=(action:string,label:string,cls='',attrs='')=>`<button data-action="${action}" class="${cls}" ${attrs}>${label}</button>`;
const wordCount=(text:string)=>text.trim().split(/\s+/).filter(Boolean).length;
const stamp=(s:string)=>new Date(s).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const duration=(n:number)=>`${Math.floor(n/60)}:${String(Math.round(n%60)).padStart(2,'0')}`;
const allIcons={LayoutDashboard,History,BookOpen,ChartNoAxesCombined,Cpu,Settings,Mic,Square,Copy,Trash2,Pin,Download,X,Check,ArrowUpRight,CircleHelp};
let refreshing:Promise<void>|null=null;
async function refresh(){
 if(refreshing)return refreshing;
 refreshing=(async()=>{try{state=await invoke<Snapshot>('get_state');render();}catch(e){localError=String(e);if(!state)root.innerHTML=`<main class="startup"><h1>Dictate could not connect</h1><p>${esc(e)}</p><button data-action="reload">Retry</button></main>`;}})();
 try{await refreshing;}finally{refreshing=null;}
}
async function call(command:string,args:Record<string,unknown>={}){
 if(busy)return;busy=true;localError='';
 try{await invoke(command,args);}catch(e){localError=String(e);}finally{busy=false;await refresh();}
}
function status(){return state.phase==='listening'?'Listening':state.phase==='preparing'?'Starting microphone':state.phase==='finalizing'?'Transcribing locally':state.phase==='delivering'?'Returning your words':state.settingUp?'Preparing model':state.ready?'Ready to dictate':'Set up a model';}
function recordingButton(){const listening=state.phase==='listening';const pending=['preparing','finalizing','delivering'].includes(state.phase);return button(listening?'finish':'record',icon(listening?'square':'mic')+(listening?'Finish recording':'Start recording'),'primary',(!state.ready||pending||state.data.recovery?'disabled':'') );}
function feedback(){return `<div class="feedback" aria-live="polite">${localError?`<p class="error">${esc(localError)}</p>`:''}${state.notice?`<p>${esc(state.notice)}</p>`:''}${state.data.recovery?`<section class="recovery"><h2>Your words are here</h2><p class="transcript">${esc(state.data.recovery)}</p><div class="actions">${button('copy-recovery',icon('copy')+'Copy text','primary')}${button('retry-delivery','Retry insertion in 3 seconds')}${button('discard-recovery','Dismiss')}</div></section>`:''}</div>`;}
function onboarding(){return `<section class="onboarding" aria-labelledby="setup-title"><div class="page-heading"><div><h1 id="setup-title">Make room for your voice.</h1><p>One local model. Your microphone. No account or paid service.</p></div></div><div class="setup-grid"><div><h2>Set up your speech model</h2><p>Whisper Tiny is the smallest download and supports multiple languages. You can choose a larger model later.</p><p class="meta">${esc(state.models.find(m=>m.id===state.data.preferences.model)?.name)} · ${Math.round((state.models.find(m=>m.id===state.data.preferences.model)?.bytes??0)/1e6)} MB</p>${state.settingUp?`<p id="model-progress" role="status">${esc(progress||'Preparing model…')}</p>${button('cancel-setup','Cancel setup')}`:state.ready?`<p class="success">${icon('check')} Your model is ready</p>`:button('setup','Set up recommended model','primary')}<p class="small">Downloaded files are checked before use. Once setup finishes, recognition works offline. No audio is uploaded.</p></div><div><h2>Your first dictation</h2><p>Start a short recording. If your system asks, allow microphone access. The words will be available to copy when you finish.</p><p class="small">${esc(state.capability)}</p>${recordingButton()}<p class="small">Shortcut: <kbd>${esc(state.data.preferences.shortcut)}</kbd></p>${state.shortcutError?`<p class="small">${esc(state.shortcutError)}</p>`:''}</div></div><div class="actions">${button('complete-setup',state.ready?'Start using Dictate':'Explore first')}</div></section>`;}
function row(item:Transcript){return `<article class="history-row"><div class="row-meta"><time datetime="${esc(item.timestamp)}">${stamp(item.timestamp)}</time><span>${duration(item.duration)}</span><span>${item.insertionResult==='insertedViaPaste'?'Inserted':'Available to copy'}</span></div><p class="transcript">${esc(item.correctedText)}</p>${item.correctionAudit.length?`<details><summary>${item.correctionAudit.length} dictionary correction${item.correctionAudit.length===1?'':'s'}</summary><p class="small">${item.correctionAudit.map(a=>`${esc(a.heard)} → ${esc(a.written)}`).join(' · ')}</p><p class="small">Original: ${esc(item.originalTranscript)}</p></details>`:''}<div class="row-actions">${button('copy-history',icon('copy')+'Copy','quiet',`data-id="${item.id}"`)}${button('pin-history',icon('pin')+(item.isPinned?'Unpin':'Pin'),'quiet',`data-id="${item.id}" aria-pressed="${item.isPinned}"`)}${button('delete-history',icon('trash-2')+'Delete','quiet',`data-id="${item.id}"`)}</div></article>`;}
function dashboard(){const history=state.data.history;const today=history.filter(h=>new Date(h.timestamp).toDateString()===new Date().toDateString());return `<div class="page-heading"><div><h1>Good to hear you.</h1><p>A calm place to see what Dictate is doing for you.</p></div>${recordingButton()}</div><section class="activity"><div><h2>Today</h2><strong>${today.reduce((n,h)=>n+wordCount(h.correctedText),0).toLocaleString()}</strong><p>words dictated</p></div><div class="week"><h2>Week activity</h2><p>Words captured each day</p><div class="bars">${Array.from({length:7},(_,i)=>{const day=new Date();day.setDate(day.getDate()-6+i);const n=history.filter(h=>new Date(h.timestamp).toDateString()===day.toDateString()).reduce((n,h)=>n+wordCount(h.correctedText),0);const max=Math.max(1,...Array.from({length:7},(_,j)=>{const d=new Date();d.setDate(d.getDate()-6+j);return history.filter(h=>new Date(h.timestamp).toDateString()===d.toDateString()).reduce((a,h)=>a+wordCount(h.correctedText),0);}));return `<div class="bar" title="${esc(day.toLocaleDateString())}: ${n} words"><span style="height:${Math.max(2,n/max*90)}px"></span><small>${day.toLocaleDateString(undefined,{weekday:'short'})}</small></div>`;}).join('')}</div></div></section><div class="dashboard-grid"><section class="panel"><h2>Quick actions</h2><p>Move from thought to text.</p>${['history','dictionary','models'].map(s=>`<button class="quick-action" data-section="${s}">${icon(glyphs[s])}<span>${s==='history'?'Open history':s==='dictionary'?'Shape your dictionary':'Choose a model'}</span>${icon('arrow-up-right')}</button>`).join('')}</section><section class="panel"><h2>Recent transcriptions</h2>${history.length?history.slice(0,3).map(h=>`<button class="recent" data-section="history"><span>${esc(h.correctedText)}</span><time>${stamp(h.timestamp)}</time></button>`).join(''):'<p>Your first completed dictation will appear here.</p>'}</section></div>`;}
function historyView(){const items=state.data.history.filter(h=>h.correctedText.toLowerCase().includes(search.toLowerCase()));return `<div class="page-heading"><div><h1>History</h1><p>Your words, ready when you need them.</p></div>${button('export-history',icon('download')+'Export')}</div><label class="search">Search transcripts<input id="search" value="${esc(search)}" placeholder="Find your words…" type="search"></label>${items.length?items.map(row).join(''):'<section class="empty"><h2>No transcripts here yet</h2><p>Record a short phrase, or clear your search to see earlier dictations.</p>'+recordingButton()+'</section>'}`;}
function dictionaryView(){const entries=state.data.dictionary;const edit=entries.find(e=>e.id===editing);return `<div class="page-heading"><div><h1>Dictionary</h1><p>Teach Dictate the words you use.</p></div><div class="actions">${button('import-dictionary','Import')}${button('export-dictionary','Export')}</div></div><form id="dictionary-form" class="panel"><h2>${edit?'Edit phrase':'Add a phrase'}</h2><div class="form-grid"><label>Type<select name="kind"><option value="correction" ${edit?.kind==='correction'?'selected':''}>Correction</option><option value="vocabulary" ${edit?.kind==='vocabulary'?'selected':''}>Vocabulary</option></select></label><label>Heard / preferred phrase<input name="source" required maxlength="2048" value="${esc(edit?.sourcePhrase)}" placeholder="cloud code"></label><label>Write instead (corrections only)<input name="target" maxlength="2048" value="${esc(edit?.targetPhrase)}" placeholder="Claude Code"></label></div><div class="actions"><button class="primary" type="submit">${edit?'Save changes':'Add phrase'}</button>${edit?button('cancel-edit','Cancel'):''}</div></form><div class="dictionary-list">${entries.length?entries.map(e=>`<article><div><strong>${esc(e.sourcePhrase)}</strong>${e.targetPhrase?`<span> → ${esc(e.targetPhrase)}</span>`:''}<p class="small">${esc(e.kind)}</p></div><div class="actions">${button('toggle-entry',e.isEnabled?'Enabled':'Disabled','quiet',`data-id="${e.id}" aria-pressed="${e.isEnabled}"`)}${button('edit-entry','Edit','quiet',`data-id="${e.id}"`)}${button('delete-entry',icon('trash-2'),'quiet',`data-id="${e.id}" aria-label="Delete ${esc(e.sourcePhrase)}"`)}</div></article>`).join(''):'<p class="empty">Add names as vocabulary, or a heard phrase and its preferred spelling as a correction.</p>'}</div>`;}
function modelsView(){return `<div class="page-heading"><div><h1>AI models</h1><p>Local speech recognition. No subscriptions.</p></div></div>${state.settingUp?`<div class="panel" role="status"><p id="model-progress">${esc(progress||'Preparing your model…')}</p>${button('cancel-setup','Cancel setup')}</div>`:''}<div class="model-list">${state.models.map(m=>`<article class="panel"><div><h2>${esc(m.name)}</h2><p>${m.id==='tiny'?'A small download for getting started.':m.id==='base'?'A larger model for everyday dictation.':'More memory and processing time; useful when smaller models miss words.'}</p><p class="meta">${Math.round(m.bytes/1e6)} MB · CPU · runs offline</p></div><div class="actions">${state.ready&&state.data.preferences.model===m.id?'<span class="success">Active</span>':button('select-model',state.installed.includes(m.id)?'Load model':'Download model','primary',`data-id="${m.id}" ${state.settingUp?'disabled':''}`)}${state.installed.includes(m.id)?button('remove-model','Remove','quiet',`data-id="${m.id}" ${state.settingUp?'disabled':''}`):''}</div></article>`).join('')}</div><p class="small">Whisper models are downloaded from the public whisper.cpp model repository on Hugging Face. The app verifies a pinned SHA-256 checksum before loading. Model download needs a connection; dictation does not.</p>`;}
function statistics(){const h=state.data.history;return `<div class="page-heading"><div><h1>Statistics</h1><p>Calculated from the history kept on this computer.</p></div></div><dl class="statistics"><div><dt>Words dictated</dt><dd>${h.reduce((n,i)=>n+wordCount(i.correctedText),0).toLocaleString()}</dd></div><div><dt>Sessions</dt><dd>${h.length}</dd></div><div><dt>Recording time</dt><dd>${Math.round(h.reduce((n,i)=>n+i.duration,0)/60)} min</dd></div><div><dt>Dictionary corrections</dt><dd>${h.reduce((n,i)=>n+i.correctionAudit.length,0)}</dd></div></dl><p class="small">Deleting history also removes it from these totals. Nothing is sent to an analytics service.</p>`;}
function settingsView(){const p=state.data.preferences;const options=(items:[string,string][],value:string)=>items.map(([v,label])=>`<option value="${v}" ${v===value?'selected':''}>${label}</option>`).join('');return `<div class="page-heading"><div><h1>Settings</h1><p>A few choices. A quieter workflow.</p></div></div><form id="settings-form" class="panel settings"><label>Recording mode<select name="recordingMode">${options([['holdToTalk','Hold to talk'],['clickToToggle','Click to toggle']],p.recordingMode)}</select></label><label>Shortcut<select name="shortcut">${options([['CommandOrControl+Shift+Space','Ctrl / Cmd + Shift + Space'],['CommandOrControl+Alt+Space','Ctrl / Cmd + Alt + Space'],['F8','F8']],p.shortcut)}</select></label><label>Appearance<select name="appearance">${options([['system','System'],['light','Light'],['dark','Dark']],p.appearance)}</select></label><label>Keep history<input name="keepHistory" type="checkbox" ${p.keepHistory?'checked':''}></label><label>Keep unpinned history<select name="retention">${options([['forever','Forever'],['oneDay','One day'],['oneWeek','One week'],['oneMonth','30 days']],p.retention)}</select></label><label>Try automatic insertion<input name="autoInsert" type="checkbox" ${p.autoInsert?'checked':''}></label><p class="small">${esc(state.capability)}</p><button class="primary" type="submit">Save settings</button></form><section class="panel"><h2>Your local data</h2><p>Audio is used only during recording and inference. History, dictionary, models, preferences, and undelivered text stay on this computer.</p><div class="actions">${button('clear-history','Delete all history','danger')}${button('show-setup','Show setup')}</div><p class="small">Dictate ${esc(state.version)} · ${esc(state.platform)} · MIT license · free community build</p></section>`;}
function render(){
 const theme=state.data.preferences.appearance;document.documentElement.dataset.theme=theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme;
 if(overlay){root.innerHTML=`<div class="recording-overlay"><span class="recording-dot"></span><span>${status()}</span><div class="level"><span id="level"></span></div></div>`;document.body.classList.add('overlay');return;}
 const view=({dashboard,history:historyView,dictionary:dictionaryView,models:modelsView,statistics,settings:settingsView}[section]??dashboard)();
 root.innerHTML=`<aside><div class="brand"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M5 22c5 0 3-9 8-9s5 15 10 15 4-9 10-9"/></svg><span>Dictate</span></div><nav aria-label="Main navigation">${Object.keys(names).map(s=>`<button data-section="${s}" ${section===s?'aria-current="page"':''}>${icon(glyphs[s])}${names[s]}</button>`).join('')}</nav><div class="sidebar-status"><span class="dot ${state.phase==='listening'?'recording':''}"></span><div><strong>${status()}</strong><small>LOCAL · PRIVATE · FREE</small></div></div></aside><main>${feedback()}${!state.data.preferences.onboardingDone?onboarding():view}${state.data.preferences.onboardingDone&&state.shortcutError?`<p class="shortcut-notice">${esc(state.shortcutError)}</p>`:''}${state.phase!=='idle'?`<div class="recording-bar" role="status"><span>${status()}</span><div class="level"><span id="level"></span></div>${state.phase==='listening'?button('finish','Finish'):''}${state.phase!=='delivering'?button('cancel-recording','Cancel'):''}</div>`:''}</main>`;
 createIcons({icons:allIcons});bindForms();
 const input=root.querySelector<HTMLInputElement>('#search');input?.addEventListener('input',()=>{search=input.value;const pos=input.selectionStart;render();const next=root.querySelector<HTMLInputElement>('#search');next?.focus();if(next?.type!=='search')next?.setSelectionRange(pos,pos);});
}
root.addEventListener('click',async e=>{
 const b=(e.target as Element).closest<HTMLButtonElement>('button');if(!b||b.disabled)return;
 if(b.dataset.section){section=b.dataset.section;search='';editing=null;render();return;}
 const id=b.dataset.id;const action=b.dataset.action;const history=state.data.history;const entries=state.data.dictionary;
 switch(action){
  case 'record':await call('start_recording');break;
  case 'finish':await call('finish_recording');break;
  case 'reload':location.reload();break;
  case 'cancel-recording':await invoke('cancel_recording');await refresh();break;
  case 'setup':await call('setup_model',{id:state.data.preferences.model,download:true});break;
  case 'select-model':await call('setup_model',{id,download:!state.installed.includes(id!)});break;
  case 'cancel-setup':await invoke('cancel_setup');break;
  case 'remove-model':if(await confirm('Remove this downloaded model? You can download it again later.',{title:'Remove model',kind:'warning'}))await call('remove_model',{id});break;
  case 'complete-setup':await call('save_preferences',{preferences:{...state.data.preferences,onboardingDone:true}});break;
  case 'show-setup':await call('save_preferences',{preferences:{...state.data.preferences,onboardingDone:false}});break;
  case 'copy-recovery':await call('copy_text',{text:state.data.recovery});break;
  case 'discard-recovery':if(await confirm('Dismiss this recovered transcript? If history is off, this removes its only saved copy.',{title:'Dismiss transcript',kind:'warning'}))await call('discard_recovery');break;
  case 'retry-delivery':await call('retry_delivery');break;
  case 'copy-history':await call('copy_text',{text:history.find(h=>h.id===id)?.correctedText});break;
  case 'pin-history':await call('update_history',{id,action:'pin'});break;
  case 'delete-history':if(await confirm('Delete this transcript from history?',{title:'Delete transcript',kind:'warning'}))await call('update_history',{id,action:'delete'});break;
  case 'clear-history':if(await confirm('Delete all history? Dictionary, models and pending recovery will remain.',{title:'Delete history',kind:'warning'}))await call('update_history',{id:null,action:'clear'});break;
  case 'edit-entry':editing=id!;render();break;
  case 'cancel-edit':editing=null;render();break;
  case 'toggle-entry':await call('save_dictionary',{entries:entries.map(v=>v.id===id?{...v,isEnabled:!v.isEnabled,updatedAt:new Date().toISOString()}:v)});break;
  case 'delete-entry':if(await confirm('Remove this dictionary phrase?',{title:'Remove phrase',kind:'warning'}))await call('save_dictionary',{entries:entries.filter(v=>v.id!==id)});break;
  case 'export-history':case 'export-dictionary':{const kind=action.split('-')[1];const path=await save({defaultPath:`dictate-${kind}.json`,filters:[{name:'JSON',extensions:['json']}]});if(path)await call('export_data',{path,kind});break;}
  case 'import-dictionary':{const path=await open({multiple:false,directory:false,filters:[{name:'Dictionary JSON',extensions:['json']}]});if(path)await call('import_dictionary',{path});break;}
 }
});
function bindForms(){
 root.querySelector<HTMLFormElement>('#dictionary-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=new FormData(e.target as HTMLFormElement);const kind=String(form.get('kind'));const prior=state.data.dictionary.find(v=>v.id===editing);const entry:Entry={id:prior?.id??crypto.randomUUID(),kind,sourcePhrase:String(form.get('source')).trim(),targetPhrase:kind==='correction'?String(form.get('target')).trim():null,notes:prior?.notes??null,isEnabled:prior?.isEnabled??true,createdAt:prior?.createdAt??new Date().toISOString(),updatedAt:new Date().toISOString()};await call('save_dictionary',{entries:[...state.data.dictionary.filter(v=>v.id!==entry.id),entry]});if(!localError){editing=null;render();}});
 root.querySelector<HTMLFormElement>('#settings-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=new FormData(e.target as HTMLFormElement);await call('save_preferences',{preferences:{...state.data.preferences,recordingMode:form.get('recordingMode'),shortcut:form.get('shortcut'),appearance:form.get('appearance'),keepHistory:form.has('keepHistory'),retention:form.get('retention'),autoInsert:form.has('autoInsert')}});});
}
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&state?.phase!=='idle'){void invoke('cancel_recording').catch(()=>{});}});
matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(state?.data.preferences.appearance==='system')render();});
async function initialize(){
await listen('state-changed',()=>{void refresh();});
await listen<{progress:number;stage:string}>('model-progress',e=>{progress=e.payload.stage==='loading'?'Download verified. Loading local model…':`Downloading: ${Math.round(e.payload.progress*100)}%`;const status=root.querySelector('#model-progress');if(status&&state?.settingUp)status.textContent=progress;});
await listen<number>('level',e=>{const bar=document.getElementById('level');if(bar)bar.style.width=`${Math.max(2,e.payload*100)}%`;});
await refresh();
}
void initialize().catch(e=>{root.innerHTML=`<main class="startup"><h1>Dictate could not connect</h1><p>${esc(e)}</p></main>`;});
